### ISSUE TITLE
Color Change Text Issue

### ISSUE THREAD

**Issue by WildByDesign** [M2Team/Privexec#16]
Thank you for implementing that Color Change feature. Excellent work!

I have found two bugs related to this feature. One of the bugs, I have a fix for.

Bug 1: The "Enable LPAC" text beside the checkbox does not respect the color changing of the text. Therefore, for example, if you change the background to black, all of the text changes correctly to white but the "Enable LPAC" text stays black and therefore cannot be seen.

My Github is far out of sync and therefore I can't do a simple pull request right now. So I will have to do the code here.

Line 109: https://github.com/M2Team/Privexec/blob/master/Appexec/Appexec.rc#L109

Change:
`    CHECKBOX    "Enable LPAC",IDC_LPACMODE,200,20,50,12, CS_BASE`

To (fix):
`    CHECKBOX    "",IDC_LPACMODE,200,20,10,11, CS_BASE`
`    LTEXT           "Enable Less Privileged AppContainer",IDS_APPCONTAINER_NAME,212,21,180,11`

This simple code change fixes Bug 1 right away and looks great. I have compiled and tested locally.

There is one part of that code that "should" be fixed but I do not understand. I re-used "IDS_APPCONTAINER_NAME" as a temporary part of the fix. So I need for you to fix that part before adding the fix for Bug 1.

Bug 2: This bug is more complex and I do not know how to fix. If you change the background to black, all of the foreground text turns white and looks and works as expected. Excellent.  However, when you close out of Appexec, and re-open Appexec, the blackground remains black which is good, but the text returns to black upon subsequent starts and therefore you cannot visually see any of the text at all.

Thank you for your time. Keep up the great work.

**Comment by fcharlie** [comment]
@WildByDesign  Bug2 Fixed.

**Comment by fcharlie** [comment]
Bug1 Fixed

**Comment by fcharlie** [comment]
![image](https://user-images.githubusercontent.com/6904176/51428720-f88db800-1c41-11e9-8f41-483fe560155f.png)
