### ISSUE TITLE
AppExec GUI Example

### ISSUE THREAD

**Issue by WildByDesign** [M2Team/Privexec#17]
I spent some time doing some simple GUI restructuring within the AppExec.rc file locally on my machine and have compiled and using the example currently.

- more horizontal space for Folder and Registry ACLs which often can be long
- more vertical space for App Capabilities List for easier navigation and selection
- removed Alias from Command box because Alias' are not very relevant to AppContainer *

(*) You will likely need to make some changes to the Alias code in AppExec because I removed it from AppExec.rc file in a more "hacky" type of way.

![appexec ui example](https://user-images.githubusercontent.com/26308319/51435250-68e80980-1c41-11e9-8593-0a47153371b0.png)

Anyway, please let me know what you think. I am always happy to share any changes that I have made. I can send you the code snippet from AppExec.rc file or send you compiled AppExec.exe to play around with so that you can test and see if you like the changes.

**Comment by fcharlie** [comment]
`Enable Less Privileged AppContainer`  Maybe move up, abbreviated as Enable LPAC

**Comment by WildByDesign** [comment]
That is a great idea. I will shorten the AppContainer Name text box slightly just enough to fit the abbreviated "Enable LPAC" right beside it. I will do this and show another screenshot in the next few hours.

This will actually be perfect because it will free up enough space for my next question. Do you think that it would be possible to add the AppX Manifest file import/parsing of Capabilities to AppExec program similar to Privexec?

I know that you made changes to allow unique SID creation so I assume that might make it more difficult to add AppX Manifest file import/parsing to AppExec. If possible, the AppX import is incredibly powerful and excellent for testing. Particularly, a user can have multiple AppX files, one for different testing programs once you know which Capabilities are required.

Thank you for your amazing work and dedication to programming in general. I am thankful and I appreciate your dedication to all of open source software. Great stuff!

**Comment by WildByDesign** [comment]
Here is step 2 after moving the Enable LPAC checkbox up as suggested.

Please let me know if the position of Enable LPAC checkbox is good. If yes, then I will proceed and move the other boxes up to align correctly. Thank you.

![appexec ui update](https://user-images.githubusercontent.com/26308319/51441229-5f8c8a80-1c9d-11e9-8780-51df7eff2ccb.png)

**Comment by fcharlie** [comment]
You can see the latest build, I kept the original layout, but added the button to the AppManifest in the AppContainer edit box, but the parsing of the import file is not implemented.

**Comment by WildByDesign** [comment]
Here is my latest example based on your latest code base. I think that your latest build on AppVeyor looks great and therefore I feel like we can close this thread.  If you do want any of my code changes, please let me know and I am happy to share.

![appexec ui example 3](https://user-images.githubusercontent.com/26308319/51450814-38b37000-1d00-11e9-997e-b941d9bdf173.png)
