### ISSUE TITLE
能否增加自动指定权限启动程序，并向其传递参数的功能。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [M2Team/Privexec#19]
再次打扰了。
这次的目的还是为了降权。
想法是直接降低不行，那就做个完美的中介程序。

比如 Firefox.exe 改名，原文件名用中介程序顶替。
某管理员程序，掉用 Firefox  打开网站 abc.com.
中介程序 ，读取配置文件，改变 权限 启动 Firefox，打开  abc.com。中介程序退出。

Privexec 能做这样的改动吗？
当然搞个专门的小程序更好。

要求有些过分，抱歉。😅

**Comment by fcharlie** [comment]
目前Privexec 没有这方面的计划 可以给你提供思路 中间程序启动时判断权限 然后自主决定是否降权 春节期间没有计划

**Comment by fcharlie** [comment]
你可以将 wsudo 与对应的程序分发，创建一个 Batch 脚本

```batch
@echo off
wsudo -U %~dp0app.exe %*
```

缺陷是 GUI 会出现控制台窗口闪过。

**Comment by wy16W2pIilK1xgqN** [comment]
> 你可以将 wsudo 与对应的程序分发，创建一个 Batch 脚本
> 
> ```batchfile
> @echo off
> wsudo -U %~dp0app.exe %*
> ```
> 
> 缺陷是 GUI 会出现控制台窗口闪过。



我现在的想法是用 AutoIt3 来做中介。
au3启动时会读取同名的脚本，基本能实现相应功能。
不过有两个缺点：
1.权限控制麻烦。
2. 程序相对过重，启动和响应偏慢，不适合频繁使用。

总之还是没是没好办法。
