### ISSUE TITLE
Feature Request: extend AppContainer Name support to wsudo

### ISSUE THREAD

**Issue by WildByDesign** [M2Team/Privexec#23]
Feature Request for wsudo:

wsudo has everything from Appx manifest import, capability parsing and LPAC but the only thing that wsudo is missing from Privexec/AppExec is the ability to choose AppContainer Name which then allows random SID generated based on unique AppContainer Name.

It would be great if wsudo can borrow this feature/code from AppExec codebase. I don't know if this would be easy or difficult to add this to wsudo.

I usually begin my AppContainer testing with AppExec GUI. After everything works well, I like to use wsudo to create shortcuts on the taskbar or Start menu that starts specific programs within LPAC sandbox with wsudo commands in the shortcuts. 

I have been using Less Privileged AppContainer (LPAC) sandbox successfully with Mozilla Thunderbird, Notepad++, Explorer++ and a few other programs. I use a different Appx Manifest file for each program with different capabilities.  The only problem is that they are all using the same AppContainer SID with wsudo and therefore being able to choose AppContainer Name and different SID would be great. 

Thank you for your time.

**Comment by fcharlie** [comment]
Your thoughts are good, but I am a bit busy recently and may not increase this feature so quickly.

**Comment by fcharlie** [comment]
@WildByDesign 
You can test the latest commit. If there is any problem, I should have no time to improve it recently. We are going to have a holiday (5.1-5.4).

**Comment by WildByDesign** [comment]
@fcharlie  My preliminary testing so far shows that these new wsudo changes for --appname are working 100%.

- successfully confirmed AppContainer creation/deletion with Windows Object Explorer 64
- successfully tested/confirmed both regular AppContainer and LPAC
- successfully tested with various Capabilities and Appx manifests
- successfully confirmed folder permissions for these randomly generated SIDs (AC folders)
- random SID generation per AppContainer/Package Name is working great

I have only tested various things over 30 minutes so far but everything is working as expected. Excellent!

Zero issues so far. However, I will continue testing thoroughly over the next day or more.

**Comment by WildByDesign** [comment]
Happy Holiday. I hope that you enjoy your holiday and some time off. You deserve it. Excellent work! Thank you, I appreciate the work that you do.
