### ISSUE TITLE
wsudo running in non-elevated process can't open GUI apps with -T or -S flag

### ISSUE THREAD

**Issue by lawmay00** [M2Team/Privexec#30]
Wsudo 4.0.0-rc1 running in non-elevated process can't open GUI apps (e.g. [serviwin.exe](https://www.nirsoft.net/utils/serviwin.html) or [autoruns64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)) with -T or -S flag.

Examples:

1. In Windows Run Command Box (Windows Key + R), wsudo -T [serviwin](https://www.nirsoft.net/utils/serviwin.html) fails to launch [serviwin](https://www.nirsoft.net/utils/serviwin.html)

2. In non-elevated cmd, powershell, or [pwsh](https://github.com/PowerShell/PowerShell) console, wsudo -T [serviwin](https://www.nirsoft.net/utils/serviwin.html) fails with error message: 'current process not runing in administrator'

3. Attempting to launch a GUI app (e.g. [serviwin.exe](https://www.nirsoft.net/utils/serviwin.html) or [autoruns64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)) with -T or -S flag from context menu fails e.g. using the following registry entry (in inf file AddReg format) hkcr,*\shell\runasTI\command,,,wsudo -T """%V"""

Example 3 is especially unfortunate, since it seems to prevent wsudo from launching GUI apps (e.g. [serviwin.exe](https://www.nirsoft.net/utils/serviwin.html) or [autoruns64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)) with -T or -S flag from the context menu (i.e. right clicking on the GUI app).

It appears this issue is limited to GUI apps and flags -T and -S. Evidence:

   a. Wsudo running in non-elevated process opens CUI apps (e.g. cmd.exe, powershell.exe, and [pwsh.exe](https://github.com/PowerShell/PowerShell)) with -T or -S flag without issue.

   b. Wsudo running in non-elevated process opens GUI apps (e.g. [serviwin.exe](https://www.nirsoft.net/utils/serviwin.html) or [autoruns64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)) with -A or -U flag without issue.

OS details: Windows 10 x64 Enterprise version 2004 build 19041.572

**Comment by lawmay00** [comment]
This issue also appears limited to non-elevated instances of wsudo. Evidence:

c. Wsudo running in Administrator (elevated) cmd, powershell, or [pwsh](https://github.com/PowerShell/PowerShell) console opens GUI apps (e.g. [serviwin.exe](https://www.nirsoft.net/utils/serviwin.html) or [autoruns64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)) with -T or -S flag without issue.

**Comment by fcharlie** [comment]
@lawmay00  Thank you for using wsudo. The problem you mentioned is actually a wsudo policy problem, in order to minimize the r user through -T/-S to start a privileged process.

Non-elevated wsudo requires the use of wsudo-tie agent to start privileged processes (wsudo-tie is an internal command and may change in the future), wsudo-tie is mainly used to attach to the console, so the above environment without wsudo and running on the console is not supported under.

https://github.com/M2Team/Privexec/blob/562d1cb528419b7877fa25a10e97d2a2ca5ca1ea/wsudo/wsudo.cc#L361-L370

Nevertheless, if the user needs it, I can try to support GUI programs.

**Comment by fcharlie** [comment]
@lawmay00 Please try https://github.com/M2Team/Privexec/releases/tag/4.0.0-rc2 thanks.

**Comment by lawmay00** [comment]
@fcharlie Issue appears completely fixed with release 4.0.0-rc3. I tested each example 1-3 in original post. In each case, non-elevated wsudo -T or -S opens GUI app (e.g. [serviwin.exe](https://www.nirsoft.net/utils/serviwin.html) or [autoruns64.exe](https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns)) without issue after UAC prompt. Great work!

Now that this issue is fixed, should we consider providing an installer version of Privexec/wsudo which offers the install option to add context menu entries "Run as TrustedInstaller" and "Run as System" when right-clicking on any executable file?

Thank you so much for Privexec/wsudo, which I greatly appreciate.

**Comment by fcharlie** [comment]
@lawmay00  
I added some scripts, which can be integrated into the file context menu just by right-clicking and running with administrator privileges.

see: https://github.com/M2Team/Privexec/releases/tag/4.0.0.-rc4

**Comment by lawmay00** [comment]
@fcharlie Thank you for the scripts.

Doesn't the command 'wsudo -T foo' fail unless foo is an .exe file? If so, shouldn't we add 'Run as TrustedInstaller' and 'Run as System' to the context menu only of .exe files, not all files?

Attached please find your scripts modified as described above. I also added an icon. What do you think?
[ContextMenu.zip](https://github.com/M2Team/Privexec/files/5389344/ContextMenu.zip)

**Comment by fcharlie** [comment]
> @fcharlie Thank you for the scripts.
> 
> Doesn't the command 'wsudo -T foo' fail unless foo is an .exe file? If so, shouldn't we add 'Run as TrustedInstaller' and 'Run as System' to the context menu only of .exe files, not all files?
> 
> Attached please find your scripts modified as described above. I also added an icon. What do you think?
> [ContextMenu.zip](https://github.com/M2Team/Privexec/files/5389344/ContextMenu.zip)

~~We only judge that the file extension is not necessarily correct. Users can modify the file extension and CreateProcess can still run. In addition, these files with the extension `*.cmd/*.bat/*.vb` also It may be a program that can be run and needs to be added to the registry key. My script is just a simple method. You can fork this project and create a PR after modifying it to contribute your modifications.~~

See: https://github.com/M2Team/Privexec/commit/77f7ae3f51f367df0362743f23b56e46a3f9f830

![image](https://user-images.githubusercontent.com/6904176/96246629-7c253600-0fdb-11eb-900f-e457860e4fd9.png)
