### ISSUE TITLE
SplitArgv failed (directories with spaces)

### ISSUE THREAD

**Issue by WildByDesign** [M2Team/Privexec#32]
**Issue:** 
Both Privexec and AppExec fail to execute programs from directories that contain spaces. Example: C:\Program Files\Windows NT\Accessories\wordpad.exe

**Error:**  
> Privexec SplitArgv failed
command not found 'C:\Program'

**Workaround:** 
If I manually add quotation marks around C:\Program Files\Windows NT\Accessories\wordpad.exe, such as  "C:\Program Files\Windows NT\Accessories\wordpad.exe" then Privexec and AppExec can successfully execute programs from directories that contain spaces.

**Comment by fcharlie** [comment]
I think this is not a BUG. We treat the dialog box marked in the figure below as a command line, which means that it may be a combination of multiple parameters, and the command line parameters do need to be split by spaces. Therefore, what you said It cannot be considered a BUG. Of course, Privexec needs to correctly escape the command line after using OpenFileDialog to select the file.

![image](https://user-images.githubusercontent.com/6904176/102160185-e7966180-3ebf-11eb-88be-8db426a92d76.png)

**Comment by fcharlie** [comment]
see: https://github.com/M2Team/Privexec/releases/tag/4.2.1

**Comment by WildByDesign** [comment]
The fix in 4.2.1 is working great. Thank you for the quick fix.
