### ISSUE TITLE
Hide window

### ISSUE THREAD

**Issue by ci70** [M2Team/Privexec#33]
wsudo -w -H notepad.exe does not work.

**Comment by fcharlie** [comment]
This appears to be expected behavior. When running GUI programs, we will ignore the --hide parameter.

![image](https://user-images.githubusercontent.com/6904176/103537913-3c7e3400-4ed0-11eb-9925-de85890cde00.png)

**Comment by ci70** [comment]
I doubt this is expected behaviour it works fine in nsudo.

**Comment by fcharlie** [comment]
@7wgs0gr04v so you mean you want wsudo to support `-H` hide windows like nsudo?

**Comment by ci70** [comment]
Sure yes.

**Comment by fcharlie** [comment]
Wait CI build: https://github.com/M2Team/Privexec/releases/tag/4.3.0

**Comment by ci70** [comment]
Thank.

**Comment by 7wgs0gr04v** [comment]
Still not fixed.
