### ISSUE TITLE
Can't be used normally.

### ISSUE THREAD

**Issue by fxzxmicah** [M2Team/Privexec#40]
Report Error: `Elavator::impersonation_system_token<OpenProcessToken> 句柄无效。`

**Comment by fxzxmicah** [comment]
Version 3.0.1 works normally.

**Comment by fcharlie** [comment]
Please tell me your OS version, and if `lsass.exe` exists.

Windows 11 (x64 22621.1483) does not reproduce the error

**Comment by fcharlie** [comment]
You can try running the latest version：
https://github.com/M2Team/Privexec/releases/tag/5.0.4-beta1

**Comment by fxzxmicah** [comment]
![image](https://user-images.githubusercontent.com/48860358/229357108-6cb63b0f-fa5d-468b-9372-6382f33d2d0b.png)
Still not working.
My OS version is `22623.1250`.
I'll use the old version for now and that's enough for me.

**Comment by fcharlie** [comment]
目前我这边无法重现，你的版本是 beta 预览版，不清楚是不是和这个有关，这边有时间再调查下。

我这边 lsass 进程的权限如下：
<img width="896" alt="image" src="https://user-images.githubusercontent.com/6904176/229358052-4fbc0c3d-5059-42c8-a1d9-c1ff76faeb34.png">

创建 TI 进程的逻辑：
管理员权限启动 --> 提权到 system --> 启动 TI 服务 --> 拷贝 TI Token --> 启动进程。

**Comment by fcharlie** [comment]
UPDATE: 请尝试 [https://github.com/M2Team/Privexec/releases/tag/5.0.4-beta2](https://github.com/M2Team/Privexec/releases/tag/5.0.4-beta2)，如果不行的话，要修复只能下周末了。

**Comment by fxzxmicah** [comment]
> 目前我这边无法重现，你的版本是 beta 预览版，不清楚是不是和这个有关，这边有时间再调查下。
> 
> 我这边 lsass 进程的权限如下： <img alt="image" width="896" src="https://user-images.githubusercontent.com/6904176/229358052-4fbc0c3d-5059-42c8-a1d9-c1ff76faeb34.png">
> 
> 创建 TI 进程的逻辑： 管理员权限启动 --> 提权到 system --> 启动 TI 服务 --> 拷贝 TI Token --> 启动进程。

提权到system就已经失败了。
新版本之后我再试试。
在过去能用和现在不能用之间好像与此相关的只有更新系统以及修改了Windows Defender防护选项。

**Comment by fcharlie** [comment]
> 
那可能 Windows Defender 防护选项是的 lsass 的权限有一些差别，winlogon 的 system 权限应该没有修改。

**Comment by MouriNaruto** [comment]
@fcharlie 实际上如果用户开启了 LSA 防护的话，是无法打开 lsass 进程的，于是 NSudo 后来的做法是先获取 lsass 令牌，获取不到获取当前会话 winlogon 令牌

参考：https://github.com/M2TeamArchived/NSudo/issues/79

毛利

**Comment by fcharlie** [comment]
> @fcharlie 实际上如果用户开启了 LSA 防护的话，是无法打开 lsass 进程的，于是 NSudo 后来的做法是先获取 lsass 令牌，获取不到获取当前会话 winlogon 令牌
> 
> 参考：[M2TeamArchived/NSudo#79](https://github.com/M2TeamArchived/NSudo/issues/79)
> 
> 毛利

在 [https://github.com/M2Team/Privexec/commit/306f50fb626df7840886068f1fa2f697290e0b28](https://github.com/M2Team/Privexec/commit/306f50fb626df7840886068f1fa2f697290e0b28) 中，我已经改为了支持从多个 system 进程获取令牌，其中包括了 winlogon，如果都获取不到才会失败。

**Comment by fxzxmicah** [comment]
还是不行。
很好奇为什么3.0.1版本没有问题。

**Comment by fcharlie** [comment]
> 还是不行。 很好奇为什么3.0.1版本没有问题。

这是一个疏忽，WinLogon 的 sessionId 是 1，代码中写死了 0，所以会失败，我已经回退到使用 WinLogon 了。

https://github.com/M2Team/Privexec/releases/tag/5.0.4

**Comment by fxzxmicah** [comment]
> > 还是不行。 很好奇为什么3.0.1版本没有问题。
> 
> 这是一个疏忽，WinLogon 的 sessionId 是 1，代码中写死了 0，所以会失败，我已经回退到使用 WinLogon 了。
> 
> https://github.com/M2Team/Privexec/releases/tag/5.0.4

确实可以了。

那我就要反馈第二个3.0.1正常，但是当前版本存在的问题：
未加载`Privexec.json`文件或加载失败，而且此问题从4.0.0版本开始就一直存在。

因为用的次数不多，所以没有反馈，但是其实早就想反馈了。

**Comment by fcharlie** [comment]
> > > 还是不行。 很好奇为什么3.0.1版本没有问题。
> > 
> > 
> > 这是一个疏忽，WinLogon 的 sessionId 是 1，代码中写死了 0，所以会失败，我已经回退到使用 WinLogon 了。
> > https://github.com/M2Team/Privexec/releases/tag/5.0.4
> 
> 确实可以了。
> 
> 那我就要反馈第二个3.0.1正常，但是当前版本存在的问题： 未加载`Privexec.json`文件或加载失败，而且此问题从4.0.0版本开始就一直存在。
> 
> 因为用的次数不多，所以没有反馈，但是其实早就想反馈了。

已修复，原因是 privexec 没有检查 privexe.json 目录是否存在

**Comment by fxzxmicah** [comment]
> 已修复，原因是 privexec 没有检查 privexe.json 目录是否存在

它在软件目录又生成了一个`appdata`文件夹，所以软件根目录的`Privexec.json`文件没用了？

**Comment by fcharlie** [comment]
你把之前的拷贝过去替换就可以了，这个是为了保持和 baulk 安装的一致，baulk install wsudo。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Fxzx micah ***@***.***>
发送时间: Thursday, April 6, 2023 11:33:59 PM
收件人: M2Team/Privexec ***@***.***>
抄送: Force Charlie ***@***.***>; State change ***@***.***>
主题: Re: [M2Team/Privexec] Can't be used normally. (Issue #40)


已修复，原因是 privexec 没有检查 privexe.json 目录是否存在

它在软件目录又生成了一个appdata文件夹，所以软件根目录的Privexec.json文件没用了？

―
