### ISSUE TITLE
怎么让子进程不继承父进程的权限？

### ISSUE THREAD

**Issue by ybyt-sys** [M2Team/Privexec#43]
wsudo在控制台运行时拥有了TrustedInstaller权限，当我通过这个控制台启动一个新进程，我想让他以Administrators权限启动，但无论我怎么改写运行命令，启动后的子进程都会继承父进程的TrustedInstaller权限，请求大佬指教，谢谢了

**Comment by fcharlie** [comment]
你得重新用 wsudo 按照指定权限运行。

**Comment by ybyt-sys** [comment]
> 你得重新用 wsudo 按照指定权限运行。
好吧，那我换一种方式运行
